import { useEffect, useState } from 'react'
import { projects, skills } from './data'

const Arrow = () => <span aria-hidden="true">↗</span>
const github = 'https://github.com/Rifat10478'
const linkedin = 'https://linkedin.com/in/islamul-haque-7394b5356/'

function Header() {
  const [open, setOpen] = useState(false)
  const links = [['Work','work'],['About','about'],['Services','services'],['Skills','skills'],['Contact','contact']]
  return <header><a className="logo" href="#top">RIFAT<span>.</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?'×':'☰'}</button><nav className={open?'open':''}>{links.map(([label,id])=><a onClick={()=>setOpen(false)} href={'#'+id} key={id}>{label}</a>)}<a href={github} target="_blank" rel="noreferrer">GitHub</a><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a className="nav-resume" href="/resume/Rifat.pdf" download>Resume ↓</a></nav></header>
}

function Contact() {
  const [state, setState] = useState('idle')
  const [error, setError] = useState('')
  async function submit(e) {
    e.preventDefault(); setState('loading'); setError('')
    const form = Object.fromEntries(new FormData(e.currentTarget))
    try { const r = await fetch(`${import.meta.env.VITE_API_URL || 'https://portfolio-2-d45e.onrender.com/api'}/contact/`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form)}); if(!r.ok) throw new Error(); setState('success'); e.currentTarget.reset() }
    catch { setError('Could not send right now. Please email me directly.'); setState('idle') }
  }
  return <section id="contact" className="contact section"><div><p className="eyebrow">LET’S BUILD SOMETHING</p><h2>Have a project<br/>in mind?</h2><p className="lede">Tell me about it. I’m open to full-time roles, freelance work and thoughtful collaborations.</p><a className="email" href="mailto:haqueh856@gmail.com">haqueh856@gmail.com <Arrow /></a><p className="place">Bogura, Bangladesh</p></div><form onSubmit={submit}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@company.com" /></label><label>Project type<select required name="project_type" defaultValue=""><option value="" disabled>Select an option</option><option>Full-stack application</option><option>Backend & API</option><option>React frontend</option><option>Job opportunity</option></select></label><label>Message<textarea required name="message" placeholder="A little about the project, timeline and goals." rows="4" /></label>{error && <p className="form-error" role="alert">{error}</p>}{state==='success' && <p className="form-success">Thank you — your message has been received.</p>}<button className="button" disabled={state==='loading'}>{state==='loading'?'Sending…':'Send inquiry'} <Arrow /></button></form></section>
}

export default function App() {
  const [portfolioProjects, setPortfolioProjects] = useState(projects)
  useEffect(() => {
    fetch(`${import.meta.env.VITE_API_URL || 'https://portfolio-2-d45e.onrender.com/api'}/projects/`)
      .then(response => response.ok ? response.json() : Promise.reject())
      .then(data => data.length && setPortfolioProjects(data.map((item, index) => ({ number: String(index + 1).padStart(2, '0'), title: item.title, category: item.category, description: item.short_description, image: item.image, githubUrl: item.github_url, liveUrl: item.live_url, tech: item.technologies, features: item.features }))))
      .catch(() => {})
  }, [])
  return <><Header/><main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">FULL-STACK DEVELOPER <i></i> AVAILABLE FOR OPPORTUNITIES</p><h1>I build modern<br/><em>web applications.</em></h1><p className="lede">I design reliable backend systems, practical REST APIs and considered React interfaces for products that need to work beautifully.</p><div className="actions"><a className="button" href="#work">View my work <Arrow /></a><a className="text-link" href="/resume/Rifat_CV.pdf" download>Download résumé ↓</a></div><p className="stack">Python <b>·</b> Django <b>·</b> DRF <b>·</b> React <b>·</b> MySQL</p></div><div className="terminal" aria-label="Decorative API dashboard"><div className="terminal-bar"><span></span><span></span><span></span><small>rifat/api</small></div><div className="terminal-main"><p><b>GET</b> /api/projects/</p><pre>{'{\n  "status": "ready",\n  "stack": ["Django", "React"],\n  "building": "useful things"\n}'}</pre><div className="metric"><small>API STATUS</small><strong>200 <i>●</i></strong></div></div></div></section>
<section id="about" className="intro section"><p className="eyebrow">01 — ABOUT</p><div><h2>Clear thinking,<br/>from database to browser.</h2><p className="lede">I’m Rifat, a full-stack developer focused on the engineering beneath a polished product: sound data models, dependable authentication, useful APIs and responsive interfaces.</p><div className="strengths">{['Backend architecture','REST APIs','React interfaces','Database design','Authentication'].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section id="services" className="services section"><p className="eyebrow">02 — SERVICES</p><div className="service-list">{[['01','Full-stack development','Complete web applications—from the database and Django backend through to a responsive React frontend.'],['02','Backend & API development','Well-structured Django and DRF APIs with authentication, business logic and database relationships.'],['03','Frontend development','Accessible React interfaces with reusable components, clear state and reliable API integration.']].map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><a href="#contact" aria-label={'Discuss '+s[1]}><Arrow /></a></article>)}</div></section>
<section id="work" className="work section"><div className="section-head"><div><p className="eyebrow">03 — SELECTED WORK</p><h2>Projects with<br/><em>real purpose.</em></h2></div><p>Each project is an opportunity to turn requirements into a considered, working system.</p></div><div className="project-list">{portfolioProjects.map(p=><article className="project" key={p.number}><div className="project-visual">{p.image ? <img src={p.image} alt={`${p.title} project cover`} loading="lazy" /> : <><span>{p.number}</span><div className="blocks"><i></i><i></i><i></i></div></>}</div><div className="project-info"><p className="project-cat">{p.category}</p><h3>{p.title}</h3><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="project-actions">{p.liveUrl && <a className="live-link" href={p.liveUrl} target="_blank" rel="noreferrer">Live demo <Arrow /></a>}{p.githubUrl && <a className="github-link" href={p.githubUrl} target="_blank" rel="noreferrer">View on GitHub <Arrow /></a>}<a className="case-link" href="#contact">Discuss this project <Arrow /></a></div></div></article>)}</div></section>
<section id="skills" className="skills section"><p className="eyebrow">04 — TECH STACK</p><h2>Tools chosen for<br/>the problem.</h2><div className="skill-grid">{skills.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.items}</p></article>)}</div></section>
<section className="process section"><p className="eyebrow">05 — HOW I BUILD</p><div>{[['01','Understand','Requirements, users and the problem worth solving.'],['02','Architect','Data, API and application structure.'],['03','Build','Backend, frontend and reusable components.'],['04','Test','Endpoints, authentication and core workflows.'],['05','Refine','Responsive polish, performance and experience.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="education section"><p className="eyebrow">06 — EDUCATION</p><div><p className="year">2026</p><h2>Computer Science<br/>& Technology</h2><p>TMSS Textile Engineering Institute<br/>Bangladesh</p></div></section><Contact/></main><footer><a className="logo" href="#top">RIFAT<span>.</span></a><p>Full-Stack Developer<br/>Python · Django · React</p><div><a href={github} target="_blank" rel="noreferrer">GitHub</a><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:haqueh856@gmail.com">Email</a></div><small>© 2026 Rifat. Built with intention.</small></footer></> }
